# SPDX-FileCopyrightText: Copyright Â© 2026 Idiap Research Institute <contact@idiap.ch>
# SPDX-FileContributor: William Droz <william.droz@idiap.ch>
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = "uv.lock"
precedence = "override"
SPDX-FileCopyrightText = "2026 Idiap Research Institute <contact@idiap.ch>"
SPDX-FileContributor = [
  "William Droz <william.droz@idiap.ch>",
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "README.md"
precedence = "override"
SPDX-FileCopyrightText = "2026 Idiap Research Institute <contact@idiap.ch>"
SPDX-FileContributor = [
  "William Droz <william.droz@idiap.ch>",
]
SPDX-License-Identifier = "MIT"
